# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml 

name: "Microsoft Sentinel GitHub Sync"

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-ai-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Synchronizing files to Azure Blob Storage..."
      
      az storage blob sync \
        --account-name libblobsentinelrepo \
        --destination microsoft-sentinel-github-repo \
        --source $(Build.SourcesDirectory) \
        --overwrite true