name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *' # Every day at 2 AM UTC
  workflow_dispatch: # Allow manual trigger too

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Your Fork (with Push Access)
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # gives push permissions
    
    - name: Set Up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Add Upstream and Sync
      run: |
        git remote add upstream https://github.com/Azure/Azure-Sentinel.git
        git fetch upstream
        git merge upstream/main --allow-unrelated-histories --no-edit || true
        git push origin main
